export const OPTIMIZED_ASSET_WIDTHS = [640, 1080, 1920];

export const OPTIMIZED_ASSETS = new Set<string>([
  "about-us-fact-image.jpg",
  "about-us-image-1.jpg",
  "about-us-image-2.jpg",
  "about-us-image-3.jpg",
  "about-us-image-4.jpg",
  "about-us-team-member-1.jpg",
  "about-us-team-member-2.jpg",
  "about-us-team-member-3.jpg",
  "cartelle-hero-image.jpg",
  "clothes-model-hover.jpg",
  "clothes-model.jpg",
  "hero-3.jpg",
  "hero-landing.jpg",
  "logo/Saaj Tradition Golden.png",
  "newsletter-image3.jpg",
  "reviewer-1.jpg",
  "reviewer-2.jpg",
  "reviewer-3.jpg",
  "reviewer-4.jpg",
  "reviewer-5.jpg",
  "store-collection-bags-accessories.jpg",
  "store-collection-dresses.jpg",
  "store-collection-outerwear.jpg",
  "store-collection-shoes.jpg",
  "store-collection-tops-bottoms.jpg",
  "support-hero.webp",
  "video-home-poster.jpg",
]);
